/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/wooden_boat.glb ./src/components/Ship.tsx -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    SM_Wooden_Boat_1_JFG_M_Boat_Base_1_JFG_0: THREE.Mesh
    SM_Wooden_Boat_1_JFG_M_Boat_Supports_Vertical_JFG_0: THREE.Mesh
    SM_Wooden_Boat_1_JFG_M_Boat_Supports_Horizontal_JFG_0: THREE.Mesh
    SM_Wooden_Boat_1_JFG_M_Boat_Planks_JFG_0: THREE.Mesh
    SM_Wooden_Boat_1_JFG_M_Boat_MiddlePlank_1_JFG_0: THREE.Mesh
    SM_Wooden_Boat_1_JFG_M_Boat_MiddlePlank_2_JFG_0: THREE.Mesh
  }
  materials: {
    M_Boat_Base_1_JFG: THREE.MeshStandardMaterial
    M_Boat_Supports_Vertical_JFG: THREE.MeshStandardMaterial
    M_Boat_Supports_Horizontal_JFG: THREE.MeshStandardMaterial
    M_Boat_Planks_JFG: THREE.MeshStandardMaterial
    M_Boat_MiddlePlank_1_JFG: THREE.MeshStandardMaterial
    M_Boat_MiddlePlank_2_JFG: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/wooden_boat.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.SM_Wooden_Boat_1_JFG_M_Boat_Base_1_JFG_0.geometry} material={materials.M_Boat_Base_1_JFG} />
          <mesh geometry={nodes.SM_Wooden_Boat_1_JFG_M_Boat_Supports_Vertical_JFG_0.geometry} material={materials.M_Boat_Supports_Vertical_JFG} />
          <mesh geometry={nodes.SM_Wooden_Boat_1_JFG_M_Boat_Supports_Horizontal_JFG_0.geometry} material={materials.M_Boat_Supports_Horizontal_JFG} />
          <mesh geometry={nodes.SM_Wooden_Boat_1_JFG_M_Boat_Planks_JFG_0.geometry} material={materials.M_Boat_Planks_JFG} />
          <mesh geometry={nodes.SM_Wooden_Boat_1_JFG_M_Boat_MiddlePlank_1_JFG_0.geometry} material={materials.M_Boat_MiddlePlank_1_JFG} />
          <mesh geometry={nodes.SM_Wooden_Boat_1_JFG_M_Boat_MiddlePlank_2_JFG_0.geometry} material={materials.M_Boat_MiddlePlank_2_JFG} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/wooden_boat.glb')
